apiVersion: v1
kind: Secret
metadata:
  name: workshop-api-secret
  namespace: postech
type: Opaque
data:
  JWT_SECRET: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
  POSTGRES_DSN: Q0hBTkdFX01F
  SMTP_USERNAME: Q0hBTkdFX01F
  SMTP_PASSWORD: Q0hBTkdFX01F
  ADMIN_PASSWORD: Q0hBTkdFX01FX0lOX1BST0RVQ1RJT04=
