apiVersion: v1
kind: Secret
metadata:
  name: workshop-api
type: Opaque
stringData:
  DATABASE_URL: postgres://workshop:senha@endpoint.rds.amazonaws.com:5432/workshop?sslmode=require
  JWT_SECRET: troque-este-segredo
