// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecases.go
//
// Generated by this command:
//
//	mockgen -source=./usecases.go -destination=./mocks/usecases.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entities "github.com/fiap/postech-tc1/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateRequesterUseCase is a mock of CreateRequesterUseCase interface.
type MockCreateRequesterUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateRequesterUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateRequesterUseCaseMockRecorder is the mock recorder for MockCreateRequesterUseCase.
type MockCreateRequesterUseCaseMockRecorder struct {
	mock *MockCreateRequesterUseCase
}

// NewMockCreateRequesterUseCase creates a new mock instance.
func NewMockCreateRequesterUseCase(ctrl *gomock.Controller) *MockCreateRequesterUseCase {
	mock := &MockCreateRequesterUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateRequesterUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateRequesterUseCase) EXPECT() *MockCreateRequesterUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateRequesterUseCase) Execute(ctx context.Context, c *entities.Requester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateRequesterUseCaseMockRecorder) Execute(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateRequesterUseCase)(nil).Execute), ctx, c)
}

// MockGetRequesterUseCase is a mock of GetRequesterUseCase interface.
type MockGetRequesterUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetRequesterUseCaseMockRecorder
	isgomock struct{}
}

// MockGetRequesterUseCaseMockRecorder is the mock recorder for MockGetRequesterUseCase.
type MockGetRequesterUseCaseMockRecorder struct {
	mock *MockGetRequesterUseCase
}

// NewMockGetRequesterUseCase creates a new mock instance.
func NewMockGetRequesterUseCase(ctrl *gomock.Controller) *MockGetRequesterUseCase {
	mock := &MockGetRequesterUseCase{ctrl: ctrl}
	mock.recorder = &MockGetRequesterUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetRequesterUseCase) EXPECT() *MockGetRequesterUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetRequesterUseCase) Execute(ctx context.Context, id string) (*entities.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(*entities.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetRequesterUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetRequesterUseCase)(nil).Execute), ctx, id)
}

// MockGetRequesterByDocumentUseCase is a mock of GetRequesterByDocumentUseCase interface.
type MockGetRequesterByDocumentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetRequesterByDocumentUseCaseMockRecorder
	isgomock struct{}
}

// MockGetRequesterByDocumentUseCaseMockRecorder is the mock recorder for MockGetRequesterByDocumentUseCase.
type MockGetRequesterByDocumentUseCaseMockRecorder struct {
	mock *MockGetRequesterByDocumentUseCase
}

// NewMockGetRequesterByDocumentUseCase creates a new mock instance.
func NewMockGetRequesterByDocumentUseCase(ctrl *gomock.Controller) *MockGetRequesterByDocumentUseCase {
	mock := &MockGetRequesterByDocumentUseCase{ctrl: ctrl}
	mock.recorder = &MockGetRequesterByDocumentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetRequesterByDocumentUseCase) EXPECT() *MockGetRequesterByDocumentUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetRequesterByDocumentUseCase) Execute(ctx context.Context, document string) (*entities.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, document)
	ret0, _ := ret[0].(*entities.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetRequesterByDocumentUseCaseMockRecorder) Execute(ctx, document any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetRequesterByDocumentUseCase)(nil).Execute), ctx, document)
}

// MockListRequestersUseCase is a mock of ListRequestersUseCase interface.
type MockListRequestersUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListRequestersUseCaseMockRecorder
	isgomock struct{}
}

// MockListRequestersUseCaseMockRecorder is the mock recorder for MockListRequestersUseCase.
type MockListRequestersUseCaseMockRecorder struct {
	mock *MockListRequestersUseCase
}

// NewMockListRequestersUseCase creates a new mock instance.
func NewMockListRequestersUseCase(ctrl *gomock.Controller) *MockListRequestersUseCase {
	mock := &MockListRequestersUseCase{ctrl: ctrl}
	mock.recorder = &MockListRequestersUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListRequestersUseCase) EXPECT() *MockListRequestersUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListRequestersUseCase) Execute(ctx context.Context) ([]*entities.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]*entities.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListRequestersUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListRequestersUseCase)(nil).Execute), ctx)
}

// MockUpdateRequesterUseCase is a mock of UpdateRequesterUseCase interface.
type MockUpdateRequesterUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateRequesterUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateRequesterUseCaseMockRecorder is the mock recorder for MockUpdateRequesterUseCase.
type MockUpdateRequesterUseCaseMockRecorder struct {
	mock *MockUpdateRequesterUseCase
}

// NewMockUpdateRequesterUseCase creates a new mock instance.
func NewMockUpdateRequesterUseCase(ctrl *gomock.Controller) *MockUpdateRequesterUseCase {
	mock := &MockUpdateRequesterUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateRequesterUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateRequesterUseCase) EXPECT() *MockUpdateRequesterUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateRequesterUseCase) Execute(ctx context.Context, c *entities.Requester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateRequesterUseCaseMockRecorder) Execute(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateRequesterUseCase)(nil).Execute), ctx, c)
}

// MockDeleteRequesterUseCase is a mock of DeleteRequesterUseCase interface.
type MockDeleteRequesterUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteRequesterUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteRequesterUseCaseMockRecorder is the mock recorder for MockDeleteRequesterUseCase.
type MockDeleteRequesterUseCaseMockRecorder struct {
	mock *MockDeleteRequesterUseCase
}

// NewMockDeleteRequesterUseCase creates a new mock instance.
func NewMockDeleteRequesterUseCase(ctrl *gomock.Controller) *MockDeleteRequesterUseCase {
	mock := &MockDeleteRequesterUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteRequesterUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteRequesterUseCase) EXPECT() *MockDeleteRequesterUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteRequesterUseCase) Execute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteRequesterUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteRequesterUseCase)(nil).Execute), ctx, id)
}

// MockCreateVehicleUseCase is a mock of CreateVehicleUseCase interface.
type MockCreateVehicleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateVehicleUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateVehicleUseCaseMockRecorder is the mock recorder for MockCreateVehicleUseCase.
type MockCreateVehicleUseCaseMockRecorder struct {
	mock *MockCreateVehicleUseCase
}

// NewMockCreateVehicleUseCase creates a new mock instance.
func NewMockCreateVehicleUseCase(ctrl *gomock.Controller) *MockCreateVehicleUseCase {
	mock := &MockCreateVehicleUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateVehicleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateVehicleUseCase) EXPECT() *MockCreateVehicleUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateVehicleUseCase) Execute(ctx context.Context, input entities.VehicleInput) (*entities.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*entities.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateVehicleUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateVehicleUseCase)(nil).Execute), ctx, input)
}

// MockGetVehicleUseCase is a mock of GetVehicleUseCase interface.
type MockGetVehicleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetVehicleUseCaseMockRecorder
	isgomock struct{}
}

// MockGetVehicleUseCaseMockRecorder is the mock recorder for MockGetVehicleUseCase.
type MockGetVehicleUseCaseMockRecorder struct {
	mock *MockGetVehicleUseCase
}

// NewMockGetVehicleUseCase creates a new mock instance.
func NewMockGetVehicleUseCase(ctrl *gomock.Controller) *MockGetVehicleUseCase {
	mock := &MockGetVehicleUseCase{ctrl: ctrl}
	mock.recorder = &MockGetVehicleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetVehicleUseCase) EXPECT() *MockGetVehicleUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetVehicleUseCase) Execute(ctx context.Context, id string) (*entities.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(*entities.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetVehicleUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetVehicleUseCase)(nil).Execute), ctx, id)
}

// MockListVehiclesUseCase is a mock of ListVehiclesUseCase interface.
type MockListVehiclesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListVehiclesUseCaseMockRecorder
	isgomock struct{}
}

// MockListVehiclesUseCaseMockRecorder is the mock recorder for MockListVehiclesUseCase.
type MockListVehiclesUseCaseMockRecorder struct {
	mock *MockListVehiclesUseCase
}

// NewMockListVehiclesUseCase creates a new mock instance.
func NewMockListVehiclesUseCase(ctrl *gomock.Controller) *MockListVehiclesUseCase {
	mock := &MockListVehiclesUseCase{ctrl: ctrl}
	mock.recorder = &MockListVehiclesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListVehiclesUseCase) EXPECT() *MockListVehiclesUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListVehiclesUseCase) Execute(ctx context.Context) ([]*entities.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]*entities.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListVehiclesUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListVehiclesUseCase)(nil).Execute), ctx)
}

// MockListVehiclesByRequesterUseCase is a mock of ListVehiclesByRequesterUseCase interface.
type MockListVehiclesByRequesterUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListVehiclesByRequesterUseCaseMockRecorder
	isgomock struct{}
}

// MockListVehiclesByRequesterUseCaseMockRecorder is the mock recorder for MockListVehiclesByRequesterUseCase.
type MockListVehiclesByRequesterUseCaseMockRecorder struct {
	mock *MockListVehiclesByRequesterUseCase
}

// NewMockListVehiclesByRequesterUseCase creates a new mock instance.
func NewMockListVehiclesByRequesterUseCase(ctrl *gomock.Controller) *MockListVehiclesByRequesterUseCase {
	mock := &MockListVehiclesByRequesterUseCase{ctrl: ctrl}
	mock.recorder = &MockListVehiclesByRequesterUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListVehiclesByRequesterUseCase) EXPECT() *MockListVehiclesByRequesterUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListVehiclesByRequesterUseCase) Execute(ctx context.Context, requesterID string) ([]*entities.Vehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, requesterID)
	ret0, _ := ret[0].([]*entities.Vehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListVehiclesByRequesterUseCaseMockRecorder) Execute(ctx, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListVehiclesByRequesterUseCase)(nil).Execute), ctx, requesterID)
}

// MockUpdateVehicleUseCase is a mock of UpdateVehicleUseCase interface.
type MockUpdateVehicleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateVehicleUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateVehicleUseCaseMockRecorder is the mock recorder for MockUpdateVehicleUseCase.
type MockUpdateVehicleUseCaseMockRecorder struct {
	mock *MockUpdateVehicleUseCase
}

// NewMockUpdateVehicleUseCase creates a new mock instance.
func NewMockUpdateVehicleUseCase(ctrl *gomock.Controller) *MockUpdateVehicleUseCase {
	mock := &MockUpdateVehicleUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateVehicleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateVehicleUseCase) EXPECT() *MockUpdateVehicleUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateVehicleUseCase) Execute(ctx context.Context, v *entities.Vehicle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateVehicleUseCaseMockRecorder) Execute(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateVehicleUseCase)(nil).Execute), ctx, v)
}

// MockDeleteVehicleUseCase is a mock of DeleteVehicleUseCase interface.
type MockDeleteVehicleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteVehicleUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteVehicleUseCaseMockRecorder is the mock recorder for MockDeleteVehicleUseCase.
type MockDeleteVehicleUseCaseMockRecorder struct {
	mock *MockDeleteVehicleUseCase
}

// NewMockDeleteVehicleUseCase creates a new mock instance.
func NewMockDeleteVehicleUseCase(ctrl *gomock.Controller) *MockDeleteVehicleUseCase {
	mock := &MockDeleteVehicleUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteVehicleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteVehicleUseCase) EXPECT() *MockDeleteVehicleUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteVehicleUseCase) Execute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteVehicleUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteVehicleUseCase)(nil).Execute), ctx, id)
}

// MockCreateServiceOrderUseCase is a mock of CreateServiceOrderUseCase interface.
type MockCreateServiceOrderUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateServiceOrderUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateServiceOrderUseCaseMockRecorder is the mock recorder for MockCreateServiceOrderUseCase.
type MockCreateServiceOrderUseCaseMockRecorder struct {
	mock *MockCreateServiceOrderUseCase
}

// NewMockCreateServiceOrderUseCase creates a new mock instance.
func NewMockCreateServiceOrderUseCase(ctrl *gomock.Controller) *MockCreateServiceOrderUseCase {
	mock := &MockCreateServiceOrderUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateServiceOrderUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateServiceOrderUseCase) EXPECT() *MockCreateServiceOrderUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateServiceOrderUseCase) Execute(ctx context.Context, input entities.ServiceOrderInput) (*entities.ServiceOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(*entities.ServiceOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateServiceOrderUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateServiceOrderUseCase)(nil).Execute), ctx, input)
}

// MockGetServiceOrderUseCase is a mock of GetServiceOrderUseCase interface.
type MockGetServiceOrderUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetServiceOrderUseCaseMockRecorder
	isgomock struct{}
}

// MockGetServiceOrderUseCaseMockRecorder is the mock recorder for MockGetServiceOrderUseCase.
type MockGetServiceOrderUseCaseMockRecorder struct {
	mock *MockGetServiceOrderUseCase
}

// NewMockGetServiceOrderUseCase creates a new mock instance.
func NewMockGetServiceOrderUseCase(ctrl *gomock.Controller) *MockGetServiceOrderUseCase {
	mock := &MockGetServiceOrderUseCase{ctrl: ctrl}
	mock.recorder = &MockGetServiceOrderUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetServiceOrderUseCase) EXPECT() *MockGetServiceOrderUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetServiceOrderUseCase) Execute(ctx context.Context, id string) (*entities.ServiceOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(*entities.ServiceOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetServiceOrderUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetServiceOrderUseCase)(nil).Execute), ctx, id)
}

// MockListServiceOrdersUseCase is a mock of ListServiceOrdersUseCase interface.
type MockListServiceOrdersUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListServiceOrdersUseCaseMockRecorder
	isgomock struct{}
}

// MockListServiceOrdersUseCaseMockRecorder is the mock recorder for MockListServiceOrdersUseCase.
type MockListServiceOrdersUseCaseMockRecorder struct {
	mock *MockListServiceOrdersUseCase
}

// NewMockListServiceOrdersUseCase creates a new mock instance.
func NewMockListServiceOrdersUseCase(ctrl *gomock.Controller) *MockListServiceOrdersUseCase {
	mock := &MockListServiceOrdersUseCase{ctrl: ctrl}
	mock.recorder = &MockListServiceOrdersUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListServiceOrdersUseCase) EXPECT() *MockListServiceOrdersUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListServiceOrdersUseCase) Execute(ctx context.Context) ([]*entities.ServiceOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]*entities.ServiceOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListServiceOrdersUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListServiceOrdersUseCase)(nil).Execute), ctx)
}

// MockListServiceOrdersByRequesterUseCase is a mock of ListServiceOrdersByRequesterUseCase interface.
type MockListServiceOrdersByRequesterUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListServiceOrdersByRequesterUseCaseMockRecorder
	isgomock struct{}
}

// MockListServiceOrdersByRequesterUseCaseMockRecorder is the mock recorder for MockListServiceOrdersByRequesterUseCase.
type MockListServiceOrdersByRequesterUseCaseMockRecorder struct {
	mock *MockListServiceOrdersByRequesterUseCase
}

// NewMockListServiceOrdersByRequesterUseCase creates a new mock instance.
func NewMockListServiceOrdersByRequesterUseCase(ctrl *gomock.Controller) *MockListServiceOrdersByRequesterUseCase {
	mock := &MockListServiceOrdersByRequesterUseCase{ctrl: ctrl}
	mock.recorder = &MockListServiceOrdersByRequesterUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListServiceOrdersByRequesterUseCase) EXPECT() *MockListServiceOrdersByRequesterUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListServiceOrdersByRequesterUseCase) Execute(ctx context.Context, requesterID string) ([]*entities.ServiceOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, requesterID)
	ret0, _ := ret[0].([]*entities.ServiceOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListServiceOrdersByRequesterUseCaseMockRecorder) Execute(ctx, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListServiceOrdersByRequesterUseCase)(nil).Execute), ctx, requesterID)
}

// MockUpdateServiceOrderStatusUseCase is a mock of UpdateServiceOrderStatusUseCase interface.
type MockUpdateServiceOrderStatusUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateServiceOrderStatusUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateServiceOrderStatusUseCaseMockRecorder is the mock recorder for MockUpdateServiceOrderStatusUseCase.
type MockUpdateServiceOrderStatusUseCaseMockRecorder struct {
	mock *MockUpdateServiceOrderStatusUseCase
}

// NewMockUpdateServiceOrderStatusUseCase creates a new mock instance.
func NewMockUpdateServiceOrderStatusUseCase(ctrl *gomock.Controller) *MockUpdateServiceOrderStatusUseCase {
	mock := &MockUpdateServiceOrderStatusUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateServiceOrderStatusUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateServiceOrderStatusUseCase) EXPECT() *MockUpdateServiceOrderStatusUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateServiceOrderStatusUseCase) Execute(ctx context.Context, input entities.StatusUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateServiceOrderStatusUseCaseMockRecorder) Execute(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateServiceOrderStatusUseCase)(nil).Execute), ctx, input)
}

// MockGetServiceOrderByCodeUseCase is a mock of GetServiceOrderByCodeUseCase interface.
type MockGetServiceOrderByCodeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetServiceOrderByCodeUseCaseMockRecorder
	isgomock struct{}
}

// MockGetServiceOrderByCodeUseCaseMockRecorder is the mock recorder for MockGetServiceOrderByCodeUseCase.
type MockGetServiceOrderByCodeUseCaseMockRecorder struct {
	mock *MockGetServiceOrderByCodeUseCase
}

// NewMockGetServiceOrderByCodeUseCase creates a new mock instance.
func NewMockGetServiceOrderByCodeUseCase(ctrl *gomock.Controller) *MockGetServiceOrderByCodeUseCase {
	mock := &MockGetServiceOrderByCodeUseCase{ctrl: ctrl}
	mock.recorder = &MockGetServiceOrderByCodeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetServiceOrderByCodeUseCase) EXPECT() *MockGetServiceOrderByCodeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetServiceOrderByCodeUseCase) Execute(ctx context.Context, code int, requesterDocument string) (*entities.ServiceOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, code, requesterDocument)
	ret0, _ := ret[0].(*entities.ServiceOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetServiceOrderByCodeUseCaseMockRecorder) Execute(ctx, code, requesterDocument any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetServiceOrderByCodeUseCase)(nil).Execute), ctx, code, requesterDocument)
}

// MockListServiceOrdersByDocumentUseCase is a mock of ListServiceOrdersByDocumentUseCase interface.
type MockListServiceOrdersByDocumentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListServiceOrdersByDocumentUseCaseMockRecorder
	isgomock struct{}
}

// MockListServiceOrdersByDocumentUseCaseMockRecorder is the mock recorder for MockListServiceOrdersByDocumentUseCase.
type MockListServiceOrdersByDocumentUseCaseMockRecorder struct {
	mock *MockListServiceOrdersByDocumentUseCase
}

// NewMockListServiceOrdersByDocumentUseCase creates a new mock instance.
func NewMockListServiceOrdersByDocumentUseCase(ctrl *gomock.Controller) *MockListServiceOrdersByDocumentUseCase {
	mock := &MockListServiceOrdersByDocumentUseCase{ctrl: ctrl}
	mock.recorder = &MockListServiceOrdersByDocumentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListServiceOrdersByDocumentUseCase) EXPECT() *MockListServiceOrdersByDocumentUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListServiceOrdersByDocumentUseCase) Execute(ctx context.Context, document string) ([]*entities.ServiceOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, document)
	ret0, _ := ret[0].([]*entities.ServiceOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListServiceOrdersByDocumentUseCaseMockRecorder) Execute(ctx, document any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListServiceOrdersByDocumentUseCase)(nil).Execute), ctx, document)
}

// MockUpdateServiceOrderStatusByCodeUseCase is a mock of UpdateServiceOrderStatusByCodeUseCase interface.
type MockUpdateServiceOrderStatusByCodeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateServiceOrderStatusByCodeUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateServiceOrderStatusByCodeUseCaseMockRecorder is the mock recorder for MockUpdateServiceOrderStatusByCodeUseCase.
type MockUpdateServiceOrderStatusByCodeUseCaseMockRecorder struct {
	mock *MockUpdateServiceOrderStatusByCodeUseCase
}

// NewMockUpdateServiceOrderStatusByCodeUseCase creates a new mock instance.
func NewMockUpdateServiceOrderStatusByCodeUseCase(ctrl *gomock.Controller) *MockUpdateServiceOrderStatusByCodeUseCase {
	mock := &MockUpdateServiceOrderStatusByCodeUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateServiceOrderStatusByCodeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateServiceOrderStatusByCodeUseCase) EXPECT() *MockUpdateServiceOrderStatusByCodeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateServiceOrderStatusByCodeUseCase) Execute(ctx context.Context, code int, requesterDocument string, newStatus entities.OrderStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, code, requesterDocument, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateServiceOrderStatusByCodeUseCaseMockRecorder) Execute(ctx, code, requesterDocument, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateServiceOrderStatusByCodeUseCase)(nil).Execute), ctx, code, requesterDocument, newStatus)
}

// MockUpdateServiceOrderUseCase is a mock of UpdateServiceOrderUseCase interface.
type MockUpdateServiceOrderUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateServiceOrderUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateServiceOrderUseCaseMockRecorder is the mock recorder for MockUpdateServiceOrderUseCase.
type MockUpdateServiceOrderUseCaseMockRecorder struct {
	mock *MockUpdateServiceOrderUseCase
}

// NewMockUpdateServiceOrderUseCase creates a new mock instance.
func NewMockUpdateServiceOrderUseCase(ctrl *gomock.Controller) *MockUpdateServiceOrderUseCase {
	mock := &MockUpdateServiceOrderUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateServiceOrderUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateServiceOrderUseCase) EXPECT() *MockUpdateServiceOrderUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateServiceOrderUseCase) Execute(ctx context.Context, so *entities.ServiceOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, so)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateServiceOrderUseCaseMockRecorder) Execute(ctx, so any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateServiceOrderUseCase)(nil).Execute), ctx, so)
}

// MockDeleteServiceOrderUseCase is a mock of DeleteServiceOrderUseCase interface.
type MockDeleteServiceOrderUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteServiceOrderUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteServiceOrderUseCaseMockRecorder is the mock recorder for MockDeleteServiceOrderUseCase.
type MockDeleteServiceOrderUseCaseMockRecorder struct {
	mock *MockDeleteServiceOrderUseCase
}

// NewMockDeleteServiceOrderUseCase creates a new mock instance.
func NewMockDeleteServiceOrderUseCase(ctrl *gomock.Controller) *MockDeleteServiceOrderUseCase {
	mock := &MockDeleteServiceOrderUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteServiceOrderUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteServiceOrderUseCase) EXPECT() *MockDeleteServiceOrderUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteServiceOrderUseCase) Execute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteServiceOrderUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteServiceOrderUseCase)(nil).Execute), ctx, id)
}

// MockGetAverageExecutionTimeUseCase is a mock of GetAverageExecutionTimeUseCase interface.
type MockGetAverageExecutionTimeUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetAverageExecutionTimeUseCaseMockRecorder
	isgomock struct{}
}

// MockGetAverageExecutionTimeUseCaseMockRecorder is the mock recorder for MockGetAverageExecutionTimeUseCase.
type MockGetAverageExecutionTimeUseCaseMockRecorder struct {
	mock *MockGetAverageExecutionTimeUseCase
}

// NewMockGetAverageExecutionTimeUseCase creates a new mock instance.
func NewMockGetAverageExecutionTimeUseCase(ctrl *gomock.Controller) *MockGetAverageExecutionTimeUseCase {
	mock := &MockGetAverageExecutionTimeUseCase{ctrl: ctrl}
	mock.recorder = &MockGetAverageExecutionTimeUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetAverageExecutionTimeUseCase) EXPECT() *MockGetAverageExecutionTimeUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetAverageExecutionTimeUseCase) Execute(ctx context.Context) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetAverageExecutionTimeUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetAverageExecutionTimeUseCase)(nil).Execute), ctx)
}

// MockCreateServiceUseCase is a mock of CreateServiceUseCase interface.
type MockCreateServiceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateServiceUseCaseMockRecorder
	isgomock struct{}
}

// MockCreateServiceUseCaseMockRecorder is the mock recorder for MockCreateServiceUseCase.
type MockCreateServiceUseCaseMockRecorder struct {
	mock *MockCreateServiceUseCase
}

// NewMockCreateServiceUseCase creates a new mock instance.
func NewMockCreateServiceUseCase(ctrl *gomock.Controller) *MockCreateServiceUseCase {
	mock := &MockCreateServiceUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateServiceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateServiceUseCase) EXPECT() *MockCreateServiceUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateServiceUseCase) Execute(ctx context.Context, s *entities.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateServiceUseCaseMockRecorder) Execute(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateServiceUseCase)(nil).Execute), ctx, s)
}

// MockGetServiceUseCase is a mock of GetServiceUseCase interface.
type MockGetServiceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetServiceUseCaseMockRecorder
	isgomock struct{}
}

// MockGetServiceUseCaseMockRecorder is the mock recorder for MockGetServiceUseCase.
type MockGetServiceUseCaseMockRecorder struct {
	mock *MockGetServiceUseCase
}

// NewMockGetServiceUseCase creates a new mock instance.
func NewMockGetServiceUseCase(ctrl *gomock.Controller) *MockGetServiceUseCase {
	mock := &MockGetServiceUseCase{ctrl: ctrl}
	mock.recorder = &MockGetServiceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetServiceUseCase) EXPECT() *MockGetServiceUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetServiceUseCase) Execute(ctx context.Context, id string) (*entities.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(*entities.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetServiceUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetServiceUseCase)(nil).Execute), ctx, id)
}

// MockListServicesUseCase is a mock of ListServicesUseCase interface.
type MockListServicesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListServicesUseCaseMockRecorder
	isgomock struct{}
}

// MockListServicesUseCaseMockRecorder is the mock recorder for MockListServicesUseCase.
type MockListServicesUseCaseMockRecorder struct {
	mock *MockListServicesUseCase
}

// NewMockListServicesUseCase creates a new mock instance.
func NewMockListServicesUseCase(ctrl *gomock.Controller) *MockListServicesUseCase {
	mock := &MockListServicesUseCase{ctrl: ctrl}
	mock.recorder = &MockListServicesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListServicesUseCase) EXPECT() *MockListServicesUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListServicesUseCase) Execute(ctx context.Context) ([]*entities.Service, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]*entities.Service)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListServicesUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListServicesUseCase)(nil).Execute), ctx)
}

// MockUpdateServiceUseCase is a mock of UpdateServiceUseCase interface.
type MockUpdateServiceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateServiceUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdateServiceUseCaseMockRecorder is the mock recorder for MockUpdateServiceUseCase.
type MockUpdateServiceUseCaseMockRecorder struct {
	mock *MockUpdateServiceUseCase
}

// NewMockUpdateServiceUseCase creates a new mock instance.
func NewMockUpdateServiceUseCase(ctrl *gomock.Controller) *MockUpdateServiceUseCase {
	mock := &MockUpdateServiceUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdateServiceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateServiceUseCase) EXPECT() *MockUpdateServiceUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdateServiceUseCase) Execute(ctx context.Context, s *entities.Service) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdateServiceUseCaseMockRecorder) Execute(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdateServiceUseCase)(nil).Execute), ctx, s)
}

// MockDeleteServiceUseCase is a mock of DeleteServiceUseCase interface.
type MockDeleteServiceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteServiceUseCaseMockRecorder
	isgomock struct{}
}

// MockDeleteServiceUseCaseMockRecorder is the mock recorder for MockDeleteServiceUseCase.
type MockDeleteServiceUseCaseMockRecorder struct {
	mock *MockDeleteServiceUseCase
}

// NewMockDeleteServiceUseCase creates a new mock instance.
func NewMockDeleteServiceUseCase(ctrl *gomock.Controller) *MockDeleteServiceUseCase {
	mock := &MockDeleteServiceUseCase{ctrl: ctrl}
	mock.recorder = &MockDeleteServiceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteServiceUseCase) EXPECT() *MockDeleteServiceUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeleteServiceUseCase) Execute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeleteServiceUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeleteServiceUseCase)(nil).Execute), ctx, id)
}

// MockCreatePartUseCase is a mock of CreatePartUseCase interface.
type MockCreatePartUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreatePartUseCaseMockRecorder
	isgomock struct{}
}

// MockCreatePartUseCaseMockRecorder is the mock recorder for MockCreatePartUseCase.
type MockCreatePartUseCaseMockRecorder struct {
	mock *MockCreatePartUseCase
}

// NewMockCreatePartUseCase creates a new mock instance.
func NewMockCreatePartUseCase(ctrl *gomock.Controller) *MockCreatePartUseCase {
	mock := &MockCreatePartUseCase{ctrl: ctrl}
	mock.recorder = &MockCreatePartUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatePartUseCase) EXPECT() *MockCreatePartUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreatePartUseCase) Execute(ctx context.Context, p *entities.Part) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockCreatePartUseCaseMockRecorder) Execute(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreatePartUseCase)(nil).Execute), ctx, p)
}

// MockGetPartUseCase is a mock of GetPartUseCase interface.
type MockGetPartUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockGetPartUseCaseMockRecorder
	isgomock struct{}
}

// MockGetPartUseCaseMockRecorder is the mock recorder for MockGetPartUseCase.
type MockGetPartUseCaseMockRecorder struct {
	mock *MockGetPartUseCase
}

// NewMockGetPartUseCase creates a new mock instance.
func NewMockGetPartUseCase(ctrl *gomock.Controller) *MockGetPartUseCase {
	mock := &MockGetPartUseCase{ctrl: ctrl}
	mock.recorder = &MockGetPartUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetPartUseCase) EXPECT() *MockGetPartUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetPartUseCase) Execute(ctx context.Context, id string) (*entities.Part, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(*entities.Part)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetPartUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetPartUseCase)(nil).Execute), ctx, id)
}

// MockListPartsUseCase is a mock of ListPartsUseCase interface.
type MockListPartsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockListPartsUseCaseMockRecorder
	isgomock struct{}
}

// MockListPartsUseCaseMockRecorder is the mock recorder for MockListPartsUseCase.
type MockListPartsUseCaseMockRecorder struct {
	mock *MockListPartsUseCase
}

// NewMockListPartsUseCase creates a new mock instance.
func NewMockListPartsUseCase(ctrl *gomock.Controller) *MockListPartsUseCase {
	mock := &MockListPartsUseCase{ctrl: ctrl}
	mock.recorder = &MockListPartsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListPartsUseCase) EXPECT() *MockListPartsUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockListPartsUseCase) Execute(ctx context.Context) ([]*entities.Part, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx)
	ret0, _ := ret[0].([]*entities.Part)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockListPartsUseCaseMockRecorder) Execute(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockListPartsUseCase)(nil).Execute), ctx)
}

// MockUpdatePartUseCase is a mock of UpdatePartUseCase interface.
type MockUpdatePartUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatePartUseCaseMockRecorder
	isgomock struct{}
}

// MockUpdatePartUseCaseMockRecorder is the mock recorder for MockUpdatePartUseCase.
type MockUpdatePartUseCaseMockRecorder struct {
	mock *MockUpdatePartUseCase
}

// NewMockUpdatePartUseCase creates a new mock instance.
func NewMockUpdatePartUseCase(ctrl *gomock.Controller) *MockUpdatePartUseCase {
	mock := &MockUpdatePartUseCase{ctrl: ctrl}
	mock.recorder = &MockUpdatePartUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdatePartUseCase) EXPECT() *MockUpdatePartUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockUpdatePartUseCase) Execute(ctx context.Context, p *entities.Part) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockUpdatePartUseCaseMockRecorder) Execute(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockUpdatePartUseCase)(nil).Execute), ctx, p)
}

// MockDeletePartUseCase is a mock of DeletePartUseCase interface.
type MockDeletePartUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockDeletePartUseCaseMockRecorder
	isgomock struct{}
}

// MockDeletePartUseCaseMockRecorder is the mock recorder for MockDeletePartUseCase.
type MockDeletePartUseCaseMockRecorder struct {
	mock *MockDeletePartUseCase
}

// NewMockDeletePartUseCase creates a new mock instance.
func NewMockDeletePartUseCase(ctrl *gomock.Controller) *MockDeletePartUseCase {
	mock := &MockDeletePartUseCase{ctrl: ctrl}
	mock.recorder = &MockDeletePartUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeletePartUseCase) EXPECT() *MockDeletePartUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDeletePartUseCase) Execute(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockDeletePartUseCaseMockRecorder) Execute(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDeletePartUseCase)(nil).Execute), ctx, id)
}

// MockAdjustPartStockUseCase is a mock of AdjustPartStockUseCase interface.
type MockAdjustPartStockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAdjustPartStockUseCaseMockRecorder
	isgomock struct{}
}

// MockAdjustPartStockUseCaseMockRecorder is the mock recorder for MockAdjustPartStockUseCase.
type MockAdjustPartStockUseCaseMockRecorder struct {
	mock *MockAdjustPartStockUseCase
}

// NewMockAdjustPartStockUseCase creates a new mock instance.
func NewMockAdjustPartStockUseCase(ctrl *gomock.Controller) *MockAdjustPartStockUseCase {
	mock := &MockAdjustPartStockUseCase{ctrl: ctrl}
	mock.recorder = &MockAdjustPartStockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdjustPartStockUseCase) EXPECT() *MockAdjustPartStockUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockAdjustPartStockUseCase) Execute(ctx context.Context, id string, delta int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, id, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockAdjustPartStockUseCaseMockRecorder) Execute(ctx, id, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockAdjustPartStockUseCase)(nil).Execute), ctx, id, delta)
}
