// Package docs holds the swagger generated documentation.
// This file is a placeholder — the real content is generated by:
//
//	swag init -g cmd/api/main.go -o docs
//
// Run the command above before building the project.
package docs
